### ISSUE TITLE
Local Notification issue 

### ISSUE THREAD

**Issue by uditb** [Kumulos/KumulosSdkObjectiveC#41]
I am facing issue while using Local notification with Kumulos. 

`- (void)userNotificationCenter:(UNUserNotificationCenter *)center 
didReceiveNotificationResponse:(UNNotificationResponse *)response 
         withCompletionHandler:(void (^)(void))completionHandler;`

These delegates require a custom userInfo object on receiving a delegate. With the local notification, the userInfo objects differ which results in the crashing of the app. 
`+ (instancetype) fromUserInfo:(NSDictionary*)userInfo {
    KSPushNotification* notification = [KSPushNotification new];
    NSDictionary* custom = userInfo[@"custom"];
    notification->_id = custom[@"a"][@"k.message"][@"data"][@"id"];
    notification->_aps = userInfo[@"aps"];
    notification->_data = custom[@"a"];
    notification->_url = custom[@"u"] ? [NSURL URLWithString:custom[@"u"]] : nil;
    return notification;
}`

Please suggest how to handle the local notifications. 
Thank you in advance.

**Comment by cgwyllie** [comment]
Hi @uditb,

Thanks for reporting this issue.

For the local notifications, do you require to handle them with your own notification center delegate class?

Can you please email support@kumulos.com to provide details of your Kumulos app, SDK version, and Xcode version?

Thanks,
  Chris
